export const TRAIT_DISPLAY_NAMES: Readonly<Record<string, string>> = {
  "traits/BouldersLarge": "大型石块",
  "traits/BouldersMedium": "中型石块",
  "traits/BouldersMixed": "混合型石块",
  "traits/BouldersSmall": "小型石块",
  "traits/DeepOil": "被圈闭的原油",
  "traits/FrozenCore": "冰冻核心",
  "traits/GeoActive": "活跃性地质",
  "traits/Geodes": "晶洞",
  "traits/Geodormant": "休眠性地质",
  "traits/GlaciersLarge": "大型冰川",
  "traits/IrregularOil": "不规则原油区",
  "traits/MagmaVents": "岩浆通道",
  "traits/MetalPoor": "金属贫瘠",
  "traits/MetalRich": "金属富足",
  "traits/MisalignedStart": "备选的打印舱位置",
  "traits/SlimeSplats": "粘液菌团",
  "traits/SubsurfaceOcean": "地下海洋",
  "traits/Volcanoes": "火山活跃",
  "expansion1::traits/CrashedSatellites": "坠毁的卫星群",
  "expansion1::traits/DistressSignal": "冰封之友",
  "expansion1::traits/IrregularOil": "不规则原油区",
  "expansion1::traits/LushCore": "繁茂核心",
  "expansion1::traits/MetalCaves": "金属洞穴",
  "expansion1::traits/RadioactiveCrust": "放射性地壳",
  "expansion1::traits/SubsurfaceOcean": "地下海洋",
  "expansion1::traits/Volcanoes": "火山活跃",
};
