interface Configuration {
    languages: Array<Description>;
    game: Array<Description>;
    cluster: Array<Cluster>;
    mixing: Array<Description>;
    traits: Array<Description>;
    geyser: Array<Description>;
}

const clusterNames = [
    "Terra",
    "Oceania",
    "Rime",
    "Verdante",
    "Arboria",
    "Volcanea",
    "The Badlands",
    "Aridio",
    "Oasisse",
    "Ceres",
    "Blasted Ceres",
    "Relica",
    "RelicAAAAGH",
    "Terra Cluster",
    "Oceania Cluster",
    "Squelchy Cluster",
    "Rime Cluster",
    "Verdante Cluster",
    "Arboria Cluster",
    "Volcanea Cluster",
    "The Badlands Cluster",
    "Aridio Cluster",
    "Oasisse Cluster",
    "Ceres Cluster",
    "Blasted Ceres Cluster",
    "Relica Cluster",
    "RelicAAAAGH Cluster",
    "Terrania Cluster",
    "Relica Minor Cluster",
    "Ceres Minor Cluster",
    "Folia Cluster",
    "Quagmiris Cluster",
    "Moonlet Cluster - Metallic Swampy",
    "Moonlet Cluster - The Desolands",
    "Moonlet Cluster - Frozen Forest",
    "Moonlet Cluster - Flipped",
    "Moonlet Cluster - Radioactive Ocean",
    "Moonlet Cluster - Ceres Mantle",
];

const configuration: Configuration = {
    languages: [
        { type: 0, key: "en", name: "English" },
        { type: 1, key: "zh-CN", name: "简体中文" },
    ],
    game: [
        { type: 0, key: "", name: "Base Game" },
        { type: 1, key: "", name: "Classic" },
        { type: 2, key: "", name: "Spaced Out!" },
    ],
    // prettier-ignore
    cluster: [
        { index:  0, type: 0, max: 0, prefix: "SNDST-A",   name: clusterNames[ 0], traits: "" },
        { index:  1, type: 0, max: 4, prefix: "OCAN-A",    name: clusterNames[ 1], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  2, type: 0, max: 4, prefix: "S-FRZ",     name: clusterNames[ 2], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  3, type: 0, max: 4, prefix: "LUSH-A",    name: clusterNames[ 3], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  4, type: 0, max: 4, prefix: "FRST-A",    name: clusterNames[ 4], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  5, type: 0, max: 4, prefix: "VOLCA",     name: clusterNames[ 5], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  6, type: 0, max: 4, prefix: "BAD-A",     name: clusterNames[ 6], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  7, type: 0, max: 4, prefix: "HTFST-A",   name: clusterNames[ 7], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  8, type: 0, max: 4, prefix: "OASIS-A",   name: clusterNames[ 8], traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { index:  9, type: 0, max: 4, prefix: "CER-A",     name: clusterNames[ 9], traits: "Z9ABCEFGHILMNOQ" },
        { index: 10, type: 0, max: 4, prefix: "CERS-A",    name: clusterNames[10], traits: "Z9ABCFGHILMOQ" },
        { index: 11, type: 0, max: 4, prefix: "PRE-A",     name: clusterNames[11], traits: "Z9ABCEFGHIKLMOQ" },
        { index: 12, type: 0, max: 2, prefix: "PRES-A",    name: clusterNames[12], traits: "Z9ABCEGIKLMO" },
        { index: 13, type: 1, max: 0, prefix: "V-SNDST-C", name: clusterNames[13], traits: "" },
        { index: 14, type: 1, max: 4, prefix: "V-OCAN-C",  name: clusterNames[14], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 15, type: 1, max: 4, prefix: "V-SWMP-C",  name: clusterNames[15], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 16, type: 1, max: 4, prefix: "V-SFRZ-C",  name: clusterNames[16], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 17, type: 1, max: 4, prefix: "V-LUSH-C",  name: clusterNames[17], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 18, type: 1, max: 4, prefix: "V-FRST-C",  name: clusterNames[18], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 19, type: 1, max: 4, prefix: "V-VOLCA-C", name: clusterNames[19], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 20, type: 1, max: 4, prefix: "V-BAD-C",   name: clusterNames[20], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 21, type: 1, max: 4, prefix: "V-HTFST-C", name: clusterNames[21], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 22, type: 1, max: 4, prefix: "V-OASIS-C", name: clusterNames[22], traits: "Z9ABCDEFGHIKLMNO1358" },
        { index: 23, type: 1, max: 4, prefix: "V-CER-C",   name: clusterNames[23], traits: "Z9ABCEFGHILMNO158" },
        { index: 24, type: 1, max: 4, prefix: "V-CERS-C",  name: clusterNames[24], traits: "Z9ABCFGHILMO158" },
        { index: 25, type: 1, max: 4, prefix: "V-PRE-C",   name: clusterNames[25], traits: "Z9ABCEFGHIKLMO58" },
        { index: 26, type: 1, max: 2, prefix: "V-PRES-C",  name: clusterNames[26], traits: "Z9ABCEGIKLMO5" },
        { index: 27, type: 2, max: 0, prefix: "SNDST-C",   name: clusterNames[27], traits: "" },
        { index: 28, type: 2, max: 4, prefix: "PRE-C",     name: clusterNames[28], traits: "Z9ABCEFGIKLMO58" },
        { index: 29, type: 2, max: 4, prefix: "CER-C",     name: clusterNames[29], traits: "Z9ABCEFGILMNO158" },
        { index: 30, type: 2, max: 4, prefix: "FRST-C",    name: clusterNames[30], traits: "Z9ABCEFGIKLMNO1578" },
        { index: 31, type: 2, max: 4, prefix: "SWMP-C",    name: clusterNames[31], traits: "Z9ABCEFGIKLMNO1578" },
        { index: 32, type: 2, max: 2, prefix: "M-SWMP-C",  name: clusterNames[32], traits: "ZABCEGKLMNO1245678" },
        { index: 33, type: 2, max: 2, prefix: "M-BAD-C",   name: clusterNames[33], traits: "ZABCDEGKLMNO124568" },
        { index: 34, type: 2, max: 2, prefix: "M-FRZ-C",   name: clusterNames[34], traits: "ZABCEGKLMNO124568" },
        { index: 35, type: 2, max: 2, prefix: "M-FLIP-C",  name: clusterNames[35], traits: "ZABCGLMO25" },
        { index: 36, type: 2, max: 2, prefix: "M-RAD-C",   name: clusterNames[36], traits: "ZABCEGLMO124568" },
        { index: 37, type: 2, max: 2, prefix: "M-CERS-C",  name: clusterNames[37], traits: "ZABCEGKLMO1578" },
    ],
    mixing: [
        { type: 10, key: "d2p1", name: "The Frosty Planet Pack" },
        { type: 6, key: "d2f1", name: "Ceres Fragment" },
        { type: 9, key: "d2b1", name: "Ice Cave Biome" },
        { type: 8, key: "d2b2", name: "Cool Pool Biome" },
        { type: 7, key: "d2b3", name: "Nectar Biome" },
        { type: 5, key: "d3p1", name: "The Bionic Booster Pack" },
        { type: 4, key: "d4p1", name: "The Prehistoric Planet Pack" },
        { type: 0, key: "d4f1", name: "Relica Fragment" },
        { type: 3, key: "d4b1", name: "Garden Biome" },
        { type: 2, key: "d4b2", name: "Feather Biome" },
        { type: 1, key: "d4b3", name: "Wetlands Biome" },
    ],
    geyser: [
        { type: 1, key: "steam", name: "Cool Steam Vent" },
        { type: 0, key: "hot_steam", name: "Steam Vent" },
        { type: 1, key: "hot_water", name: "Water Geyser" },
        { type: 1, key: "slush_water", name: "Cool Slush Geyser" },
        { type: 1, key: "filthy_water", name: "Polluted Water Vent" },
        { type: 1, key: "slush_salt_water", name: "Cool Salt Slush Geyser" },
        { type: 1, key: "salt_water", name: "Salt Water Geyser" },
        { type: 0, key: "small_volcano", name: "Minor Volcano" },
        { type: 0, key: "big_volcano", name: "Volcano" },
        { type: 2, key: "liquid_co2", name: "Carbon Dioxide Geyser" },
        { type: 2, key: "hot_co2", name: "Carbon Dioxide Vent" },
        { type: 2, key: "hot_hydrogen", name: "Hydrogen Vent" },
        { type: 2, key: "hot_po2", name: "Hot Polluted Oxygen Vent" },
        { type: 2, key: "slimy_po2", name: "InFectious Polluted Oxygen Vent" },
        { type: 2, key: "chlorine_gas", name: "Chlorine Gas Vent" },
        { type: 0, key: "methane", name: "Natural Gas Geyser" },
        { type: 0, key: "molten_copper", name: "Copper Volcano" },
        { type: 0, key: "molten_iron", name: "Iron Volcano" },
        { type: 0, key: "molten_gold", name: "Gold Volcano" },
        { type: 0, key: "molten_aluminum", name: "Aluminum Volcano" },
        { type: 0, key: "molten_cobalt", name: "Cobalt Volcano" },
        { type: 0, key: "oil_drip", name: "Leaky Oil Fissure" },
        { type: 0, key: "liquid_sulfur", name: "Liquid Sulfur Geyser" },
        { type: 0, key: "chlorine_gas_cool", name: "Cool Chlorine Gas Vent" },
        { type: 0, key: "molten_tungsten", name: "Tungsten Volcano" },
        { type: 0, key: "molten_niobium", name: "Niobium Volcano" },
        { type: 0, key: "printpod", name: "Printing Pod" },
        { type: 0, key: "oil_reservoir", name: "Oil Reservoir" },
        { type: 0, key: "receiver", name: "Supply Teleporter Output" },
        { type: 0, key: "sender", name: "Supply Teleporter Input" },
        { type: 0, key: "teleporter", name: "Teleporter Transmitter" },
        { type: 0, key: "cryopod", name: "Cryotank 3000" },
    ],
    traits: [
        { type: 0, key: "0", name: "No Traits" },
        { type: 0, key: "1", name: "Crashed Satellites" },
        { type: 0, key: "2", name: "Frozen Friend" },
        { type: 0, key: "3", name: "Irregular Oil" },
        { type: 0, key: "4", name: "Lush Core" },
        { type: 0, key: "5", name: "Metallic Caves" },
        { type: 0, key: "6", name: "Radioactive Crust" },
        { type: 0, key: "7", name: "Subsurface Ocean" },
        { type: 0, key: "8", name: "Volcanic Activity" },
        { type: 2, key: "9", name: "Large Boulders" },
        { type: 0, key: "A", name: "Medium Boulders" },
        { type: 2, key: "B", name: "Mixed Boulders" },
        { type: 0, key: "C", name: "Small Boulders" },
        { type: 0, key: "D", name: "Trapped Oil" },
        { type: 0, key: "E", name: "Frozen Core" },
        { type: 1, key: "F", name: "Geoactive" },
        { type: 1, key: "G", name: "Geodes" },
        { type: 2, key: "H", name: "Geodormant" },
        { type: 0, key: "I", name: "Large Claciers" },
        { type: 0, key: "J", name: "Irregular Oil" },
        { type: 0, key: "K", name: "Magma Channels" },
        { type: 2, key: "L", name: "Metal Poor" },
        { type: 1, key: "M", name: "Metal Rich" },
        { type: 0, key: "N", name: "Alternate Pod Location" },
        { type: 0, key: "O", name: "Slime Molds" },
        { type: 0, key: "P", name: "Subsurface Ocean" },
        { type: 0, key: "Q", name: "Volcanic Activity" },
        { type: 0, key: "Z", name: "Any Trait" },
    ],
};

export default configuration;
